name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checar o código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Fazer login no Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.user_docker }}
        password: ${{ secrets.senha_docker }}

    # 3. Construir e enviar a imagem para o Docker Hub
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.user_docker }}/flask-app:latest .
        docker push ${{ secrets.senha_docker }}/flask-app:latest

    # 4. Deploy automático na Vercel
    - name: Deploy to Vercel
      run: |
        npm install -g vercel
        vercel deploy --token ${{ secrets.VERCEL_GITHUB }} --yes --prod
